import random
from typing import Dict, Any, Tuple

class SatelliteEnv:
    """
    PIXEL Satellite Network Environment
    Simulates a multi-agent satellite system (SAT-A, SAT-B, SAT-C) coordinating
    communication, energy, and orbital decisions under real-world constraints.
    """
    
    def __init__(self):
        self.max_network_bandwidth = 100
        self.reset()

    def reset(self) -> str:
        self.network_load = 0
        self.collision_risk = random.uniform(0.0, 0.1)
        self.satellites = {
            "SAT-A": {
                "id": "SAT-A",
                "role": "Communication",
                "battery": 100.0,
                "data_buffer": 0,
                "bandwidth_available": self.max_network_bandwidth,
                "position": [random.uniform(-90, 90), random.uniform(-180, 180)],
                "visible_to_earth": True,
                "visible_to_relay": True
            },
            "SAT-B": {
                "id": "SAT-B",
                "role": "Imaging",
                "battery": 100.0,
                "data_buffer": random.randint(50, 150),
                "bandwidth_available": 0, # Depends on SAT-A or SAT-C
                "position": [random.uniform(-90, 90), random.uniform(-180, 180)],
                "visible_to_earth": False,
                "visible_to_relay": True
            },
            "SAT-C": {
                "id": "SAT-C",
                "role": "Relay",
                "battery": 100.0,
                "data_buffer": 0,
                "bandwidth_available": 0,
                "position": [random.uniform(-90, 90), random.uniform(-180, 180)],
                "visible_to_earth": True,
                "visible_to_relay": True
            }
        }
        self.step_count = 0
        return self._generate_observation()

    def state(self) -> Dict[str, Any]:
        return {
            "satellites": list(self.satellites.values()),
            "network_load": self.network_load,
            "collision_risk": self.collision_risk,
            "step": self.step_count
        }

    def _generate_observation(self) -> str:
        s = self.state()
        obs = f"Step {self.step_count} | Network Load: {s['network_load']} | Collision Risk: {s['collision_risk']:.2f}\n"
        for sat in s['satellites']:
            obs += f"{sat['id']} ({sat['role']}) - Battery: {sat['battery']}%, Buffer: {sat['data_buffer']}MB\n"
        return obs

    def step(self, action: str) -> Tuple[str, float, bool, Dict[str, Any]]:
        self.step_count += 1
        reward = 0.0
        info = {"action": action, "conflict": False}
        
        # Parse action (Expected format: "SAT-X: action")
        # Supported actions: transmit_data, delay_transmission, route_via_relay, adjust_orbit, low_power_mode
        
        # Environmental updates
        self.collision_risk += random.uniform(-0.05, 0.05)
        self.collision_risk = max(0.0, min(1.0, self.collision_risk))
        
        # New data generated by Imaging Satellite (SAT-B)
        if random.random() < 0.4:
            self.satellites["SAT-B"]["data_buffer"] += random.randint(20, 50)
            
        action_parts = action.split(":", 1)
        if len(action_parts) == 2:
            target_sat = action_parts[0].strip()
            cmd = action_parts[1].strip()
            
            if target_sat in self.satellites:
                sat = self.satellites[target_sat]
                
                if cmd == "transmit_data":
                    if sat["data_buffer"] > 0:
                        if sat["visible_to_earth"]:
                            if self.network_load + 50 <= self.max_network_bandwidth:
                                self.network_load += 50
                                sat["data_buffer"] = max(0, sat["data_buffer"] - 50)
                                sat["battery"] -= 10
                                reward += 1.0 # Successful transmission
                            else:
                                reward -= 1.0 # Conflict / Bandwidth full
                                info["conflict"] = True
                        else:
                            reward -= 1.0 # Cannot transmit without visibility
                            sat["battery"] -= 5 # Energy waste
                    else:
                        reward -= 0.5 # Energy waste (nothing to transmit)
                        sat["battery"] -= 2
                        
                elif cmd == "route_via_relay":
                    if target_sat == "SAT-B" and sat["data_buffer"] > 0:
                        if sat["visible_to_relay"] and self.satellites["SAT-C"]["battery"] > 10:
                            # Transfer data to relay
                            transfer_amount = min(sat["data_buffer"], 50)
                            sat["data_buffer"] -= transfer_amount
                            sat["battery"] -= 5
                            self.satellites["SAT-C"]["data_buffer"] += transfer_amount
                            self.satellites["SAT-C"]["battery"] -= 5
                            reward += 0.5 # Efficient routing
                        else:
                            reward -= 0.5 # Failed routing
                    else:
                        reward -= 0.5 # Invalid routing attempt
                        
                elif cmd == "delay_transmission":
                    reward += 0.2 # Safe behavior
                    sat["battery"] += 2 # slight recovery
                    
                elif cmd == "adjust_orbit":
                    if self.collision_risk > 0.2:
                        self.collision_risk *= 0.5
                        sat["battery"] -= 15
                        reward += 0.5 # Averted collision
                    else:
                        sat["battery"] -= 15
                        reward -= 0.5 # Energy waste
                        
                elif cmd == "low_power_mode":
                    sat["battery"] = min(100.0, sat["battery"] + 10)
                    reward += 0.2
                    
                else:
                    reward -= 0.1 # Unknown command
            else:
                reward -= 0.1 # Unknown satellite
        else:
            reward -= 0.1 # Invalid action format
            
        # Drain battery slightly for all satellites
        for s in self.satellites.values():
            s["battery"] = max(0.0, s["battery"] - 1.0)
            if s["battery"] <= 0:
                reward -= 1.0 # Failure due to dead battery
                
        # Natural bandwidth decay (clearing the network)
        self.network_load = max(0, self.network_load - 20)
        
        done = self.step_count >= 100 or any(s["battery"] <= 0 for s in self.satellites.values())
        
        return self._generate_observation(), reward, done, info
